apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demo-app-podmonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: demo-app
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - port: http-web
      path: /metrics
      interval: 15s
